CREATE TABLE COLABORADOR(
CPF VARCHAR2 (11) NOT NULL,
NOME VARCHAR2 (100) NOT NULL,
CONSTRAINT COLABORADOR_PK PRIMARY KEY(CPF) ENABLE
);

CREATE TABLE CAFEMANHA(
ID_CAFE NUMBER NOT NULL,
ITEMCAFE VARCHAR2(100) NOT NULL,
CPFCOLABORADOR VARCHAR(11) NOT NULL,

CONSTRAINT ID_CAFE_PK PRIMARY KEY (ID_CAFE) ENABLE,
CONSTRAINT CPFCOLABORADOR_FK FOREIGN KEY (CPFCOLABORADOR) REFERENCES COLABORADOR(CPF) ENABLE
);

CREATE SEQUENCE S_ID_CAFE INCREMENT BY 1 START WITH 1 MINVALUE 1;